"""hastaya access_token eklendi

Revision ID: 56d89e605e05
Revises: a77644a3d864
Create Date: 2026-07-08 01:16:14.093412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d89e605e05'
down_revision: Union[str, None] = 'a77644a3d864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Once nullable ekle, mevcut hastalar icin benzersiz token uret, sonra NOT NULL yap.
    op.add_column('patients', sa.Column('access_token', sa.String(length=64), nullable=True))
    op.execute(
        "UPDATE patients SET access_token = replace(gen_random_uuid()::text, '-', '') "
        "WHERE access_token IS NULL"
    )
    op.alter_column('patients', 'access_token', nullable=False)
    op.create_index(op.f('ix_patients_access_token'), 'patients', ['access_token'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_access_token'), table_name='patients')
    op.drop_column('patients', 'access_token')
    # ### end Alembic commands ###
