"""users tablosuna clinic_id eklendi

Revision ID: a77644a3d864
Revises: c053c652597c
Create Date: 2026-06-24 21:42:28.244864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77644a3d864'
down_revision: Union[str, None] = 'c053c652597c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clinic_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_foreign_key(
        'fk_users_clinic_id_clinics', 'users', 'clinics', ['clinic_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_clinic_id_clinics', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_column('users', 'clinic_id')
    # ### end Alembic commands ###
