"""klinik intake_token ve hasta notes eklendi

Revision ID: e712e32008c5
Revises: 56d89e605e05
Create Date: 2026-07-08 14:23:13.958280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e712e32008c5'
down_revision: Union[str, None] = '56d89e605e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # intake_token: once nullable ekle, mevcut klinikler icin token uret, NOT NULL yap
    op.add_column('clinics', sa.Column('intake_token', sa.String(length=64), nullable=True))
    op.execute(
        "UPDATE clinics SET intake_token = replace(gen_random_uuid()::text, '-', '') "
        "WHERE intake_token IS NULL"
    )
    op.alter_column('clinics', 'intake_token', nullable=False)
    op.create_index(op.f('ix_clinics_intake_token'), 'clinics', ['intake_token'], unique=True)
    # notes nullable oldugu icin backfill gerekmez
    op.add_column('patients', sa.Column('notes', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'notes')
    op.drop_index(op.f('ix_clinics_intake_token'), table_name='clinics')
    op.drop_column('clinics', 'intake_token')
    # ### end Alembic commands ###
